# Generated by Django 3.1.3 on 2020-11-30 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chofer_distrito', to='cliente.distrito'),
        ),
        migrations.AddField(
            model_name='chofer',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chofer_empresa', to='cliente.empresa'),
        ),
    ]
