# Generated by Django 3.1.3 on 2020-12-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20201129_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='fecha_caducidad_licencia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Caducidad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='empresa',
            field=models.CharField(max_length=250, verbose_name='Empresa'),
        ),
    ]
