# Generated by Django 3.1.3 on 2020-12-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20201129_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='empresa',
            field=models.CharField(max_length=250, verbose_name='Empresa'),
        ),
    ]
