# Generated by Django 3.1.3 on 2020-12-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20201216_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='fecha_inicio_licencia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
