# Generated by Django 3.1.3 on 2020-12-17 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20201215_1749'),
        ('cliente', '0003_auto_20201216_1846'),
    ]

    operations = [
    ]
