# Generated by Django 3.1.3 on 2020-12-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_chofer_fecha_inicio_licencia'),
        ('cliente', '0004_merge_20201217_0018'),
    ]

    operations = [
    ]
